### ISSUE TITLE
KeyError:0 when processing a mzML file

### ISSUE THREAD

**Issue by MarcIsak** [markmipt/biosaur2#3]
Hi, 

I tried to run biosaur2 on a test sample acquired with DDA on a TimsTOF Pro. I converted the *.d file to a mzML with the options 
--combineIonMobilitySpectra and --filter "msLevel 1". Towards the end of the processing, I get an error referring to a KeyError=0 (see below). 

Any idea what could be wrong here? 

biosaur2 -tof -debug -o /data/biosaur2/ /data/biosaur2/220609\ \ Full\ scan\ 10uL_1\ sample3_S1-A1_1_4577.mzML
    DEBUG: [18:07:48] Starting with args: {'files': ['/data/biosaur2/220609  Full scan 10uL_1 sample3_S1-A1_1_4577.mzML'], 'mini': 1, 'minmz': 350, 'maxmz': 1500, 'pasefmini': 100, 'htol': 8, 'itol': 8, 'paseftol': 0.05, 'nm': 0, 'o': '/data/biosaur2/', 'hvf': 1.3, 'minlh': 2, 'pasefminlh': 1, 'cmin': 1, 'cmax': 6, 'nprocs': 4, 'dia': False, 'diahtol': 25, 'diaminlh': 1, 'mgf': '', 'debug': True, 'tof': True, 'profile': False}

INFO: [13:59:39] Starting file: /data/biosaur2/220609  Full scan 10uL_1 sample3_S1-A1_1_4577.mzML
INFO: [14:00:56] Number of MS1 scans: 5509
INFO: [14:00:56] Number of skipped MS1 scans: 0
INFO: [14:02:00] PASEF scans analysis: 1/4635
INFO: [14:02:00] number of m/z peaks in scan: 12
...
INFO: [14:34:40] PASEF scans analysis: 4635/4635
INFO: [14:34:40] number of m/z peaks in scan: 598
INFO: [14:34:40] number of m/z peaks in scan after centroiding: 391
INFO: [14:34:40] Number of MS1 scans after combining ion mobility peaks: 4635
Traceback (most recent call last):
  File "/opt/conda/envs/biosaur/bin/biosaur2", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/envs/biosaur/lib/python3.8/site-packages/biosaur2/search.py", line 70, in run
    main.process_file(deepcopy(args))
  File "/opt/conda/envs/biosaur/lib/python3.8/site-packages/biosaur2/main.py", line 165, in process_file
    hills_dict = detect_hills(data_for_analyse_tmp, args, mz_step, paseftol)
  File "biosaur2/cutils.pyx", line 579, in biosaur2.cutils.detect_hills
KeyError: 0

**Comment by MarcIsak** [comment]
By the way, I used the latest Biosaur2=0.1.9.2 with Python 3.8.

**Comment by markmipt** [comment]
Dear Marc,

Thanks for the report! Could you please try a new version (0.2.1) of biosaur2 and check it works fine now? It will be compiled and uploaded automatically to PyPi within a few hours or you can directly install it from the latest commit in the master branch.

Regards,
Mark

**Comment by MarcIsak** [comment]
Thanks! Looking forward to test the new version soon. I just wonder, since I have TimsTOF DDA data (DDA-PASEF), should I use the **-tof** flag?

**Comment by markmipt** [comment]
Basically, the "-tof" flag estimates noise intensity distribution across m/z range and automatically calculates intensity cutoffs for different m/z value ranges. An alternative way to reduce noise is "-mini" option which is a fixed intensity threshold for all m/z values.

I'm using peptide features mostly for protein identification using MS1-only spectra and I can get some satisfactory results for TimsTOF data in both cases of using and not using of "-tof" flag. But I have almost no experience for DDA-PASEF data analysis, so it is hard to give any advises here.

**Comment by MarcIsak** [comment]
So, the new biosaur2 version seems to have solved the issue I had. Now I can get TSV-files with features generated for each processed mzML-file. 

Good job and thank you for the fix and explanation of the -tof flag!

I will close this issue now.
