### ISSUE TITLE
v0.2.8 not published to pypi

### ISSUE THREAD

**Issue by seantur** [markmipt/biosaur2#5]
biosaur2 0.2.7 is published to pypi, but 0.2.8 is not: https://pypi.org/project/biosaur2/#history

 It looks like the 0.2.7 version was git tagged as v0.2.8 to trigger the github action: https://github.com/markmipt/biosaur2/blob/v0.2.8/VERSION

**Comment by markmipt** [comment]
Thanks for noticing! Github actions will upload the new release on the PyPi within a few hours.

Regards,
Mark

**Comment by seantur** [comment]
Thanks!
