### ISSUE TITLE
Question of detailed algorithm

### ISSUE THREAD

**Issue by ghost** [markmipt/biosaur2#7]
Hi Dr. Ivanov,

According to your response (https://github.com/abdrakhimov1/Biosaur/issues/22), I have downloaded your IQMMA tool and it works well with our MS-GF+ results. Thanks.

Meanwhile, i am curious about the detailed algorithm which IQMMA and, especially Biosaur2, uses. Since I am new to the algorithms of feature extracting and peak picking, there are some codes which I don't know what they are used for. Could you please give me a brief explanation about the meaning of them if possible? Thanks again for your reply!

In the cutils.pyx file of Biosaur2 (https://github.com/markmipt/biosaur2/blob/main/biosaur2/cutils.pyx), line 359-385,
` 
    while idx <= c_len:

                if len(min_idx_list) and idx >= min_idx_list[-1] + min_length_hill:
                    l_idx = min_idx_list[-1]

                l_r = max(smothed_intensity[l_idx:idx]) / float(smothed_intensity[idx])
                if l_r >= hillValleyFactor:
                    r_r = max(smothed_intensity[idx+1:]) / float(smothed_intensity[idx])
                    if r_r >= hillValleyFactor:
                        mult_val = l_r * r_r
                        include_factor = (1 if l_r > r_r else 0)
                        if (min_length_hill <= idx + include_factor <= c_len):
                            if not len(min_idx_list) or idx + include_factor >= min_idx_list[-1] + min_length_hill:
                                min_idx_list.append(idx + include_factor)
                                recheck_r_r.append(idx)
                                min_val = mult_val
                            elif mult_val > min_val:
                                min_idx_list[-1] = idx + include_factor
                                recheck_r_r[-1] = idx
                                min_val = mult_val
                idx += 1
            if len(min_idx_list):
                for min_idx, end_idx, recheck_idx in zip(min_idx_list, min_idx_list[1:] + [idx_start+hill_length, ], recheck_r_r):
                    r_r = max(smothed_intensity[recheck_idx+1:end_idx]) / float(smothed_intensity[recheck_idx])
                    if r_r >= hillValleyFactor:
                        new_index_list[idx_start+min_idx:idx_start+hill_length] = cur_new_idx
                        cur_new_idx += 1

`

I realize that these lines of codes might be an evaluation of the shapes of hills, but I can't figure out how the hillValleyFactor can evaluate them and what these codes exactly do. Could you please give me some brief detailed annotations or references?

Best wishes and thank you very much !!

**Comment by markmipt** [comment]
Hi Jim!

Thanks again for your interest!

As for the mentioned code and -hfv (hillValleyFactor) biosaur2 option used here:
At the first stage, biosaur2 combine all the m/z with close values in different MS1 scans into the hills (RT profiles of m/z peaks). If two peptides have intersection in RT profiles they will have one combined hill with local minimum in the middle of RT profile. biosaur2 analyses hills and split them into multiple (can be more than two!) hills. The condition to split is hvf option which is threshold to split hills into multiple if local minimum intensity multiplied by hvf is less than both surrounding local maximums. All peaks after splitting must have at least max(2 or "minlh option") MS1 scans. Intensities are smoothed by mean filtering to reduce noise.
![HVF_example](https://user-images.githubusercontent.com/12832559/228494570-da5ea684-37a8-4b5f-8ff7-5677e01d38e5.jpg)


P.S. I've updated README on the github with description of all options available for biosaur2. Hope that would help.

Regards,
Mark

**Comment by ghost** [comment]
Hi Dr. Ivanov,
Thank you very much for your kind reply. The explanation and the README page is helpful.
It does help a lot and I think now I know how's the hillValleyFactor works. But there's still a little problem about what the "recheck_r_r" array is used for. 

Does it record the indexes of selected "local minimums" by calculating (suppose the current index as x:
 max(x: right side of XIC/hill) / intensity(x)

and I wonder why a second time calculation of "r_r" is performed in the "for loop" (codes below) ... ? Since the "r_r" in "recheck_r_r" are selected at the same time when "l_r" are calculated.

```
if len(min_idx_list):
    for min_idx, end_idx, recheck_idx in zip(min_idx_list, min_idx_list[1:] + [idx_start + hill_length, ],
                                                         recheck_r_r):
        r_r = max(smothed_intensity[recheck_idx + 1:end_idx]) / float(smothed_intensity[recheck_idx])
        if r_r >= hillValleyFactor:
                new_index_list[idx_start + min_idx:idx_start + hill_length] = cur_new_idx
                cur_new_idx += 1
```

Thanks again for your response and I really learn a lot communicating with you. : )

Best wishes,
Jim

**Comment by markmipt** [comment]
recheck_r_r is an array that contains all potential local minimums. However, when r_r is calculated in the first time, we don't know yet the number of local maximums. Thus, r_r is calculated using the max intensity from the right side of minimum till the end of hill. But what we really want - to calculate r_r from the right side of minimum **till the next local minumum** . That is why there is a second time calculation

![HVF_example2](https://user-images.githubusercontent.com/12832559/228579890-848417be-f4a9-4070-a456-63afc1dcb14d.jpg)

**Comment by ghost** [comment]
Hi Dr. Ivanov,
I greatly appreciate your response and explanation and now I think I totally understand how the algorithm works. The design of codes is quite elaborate. Thank you sooooo much for the thorough explanation. I have really learned a lot from your programs and articles.
Best wishes : )
